import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import "@uploadthing/react/styles.css";
import Nav from './components/Nav';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Visual Search',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body className={inter.className}>
      <Nav></Nav>
        <main className='container'>
          <div >
            <div className='p-1'>
            {children}
            </div>
          </div>
        </main>
        
        </body>
    </html>
    </ClerkProvider>
  )
}
